name: Windows 32-bit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-win32:
    if: github.actor != 'dependabot[bot]'
    runs-on: ${{ matrix.os }}
    name: Check action on 32bit windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        cmake_ver: ['', '3.19.3', '3.15.1', '2.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup cmake
        uses: ./
        id: setup
        with:
          cmake-version: ${{ matrix.cmake_ver }}
          use-32bit: 'true'

      - name: Run cmake --version
        shell: bash
        if: ${{ matrix.cmake_ver != '' }}
        run: |
          VERSION=`cmake --version`
          echo $VERSION
          [[ "$VERSION" =~ "${{ matrix.cmake_ver }}" ]]

      - name: Run cmake --version
        shell: bash
        if: ${{ matrix.cmake_ver == '' }}
        run: |
          cmake --version
